image: node:latest

cache:
  paths:
    - node_modules/
    - functions/node_modules/
    - frontend/node_modules/

deploy_production:
  stage: deploy
  environment: Production
  script:
    - npm install -g firebase-tools
    - npm install
    - cd functions
    - npm install
    - cd ../frontend
    - npm install
    - npm run build
    - cd ..
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY --project $FIREBASE_PROJECT_ID